spring:
  application:
  name: parkee-backend-engineer-test
  datasource:
    url: jdbc:sqlserver://;serverName=localhost;databaseName=dbParkee;encrypt=true;trustServerCertificate=true;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update